name: myportfolio
favicon: null
layout_spectrum: 0.0414875668939203
typography_spectrum: 0.8626440514344722
title: Development Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4174742875620723
  lightness: 0.13506090105511248
  saturation: 0.1662792251445353
  rhythmicContrast: 0.9758564685471356
purpose: []
