name: myportfolio
favicon: null
layout_spectrum: 0.75619
typography_spectrum: 0.2265
title: Development Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#1976d2'
    - '#ffffff'
    - '#5a595b'
    - '#ffab40'
  brandStrength: 0.4174742875620723
  lightness: 0.13506090105511248
  saturation: 0.1662792251445353
  rhythmicContrast: 0.9758564685471356
purpose: []
